### ISSUE TITLE
Each file is changed, images become corrupt

### ISSUE THREAD

**Issue by brinkdinges** [kuanysh-nabiyev/RenameProjectVsExtension#14]
First of all, thank you for taking the time to create this extension. It saved me a lot of manual work. I had two issues though and one of them might be an easy fix. 

The first one is not really your fault I think. I once created a new solution with a new project, so Visual Studio uses the same name for both. My goal today was to rename the project first and the solution to something else later. When I tried to rename the project, 95% of all files changed correctly. All of my XAML files still had references to the old project. That might be because the name of the solution is identical, but maybe you can change the algorithm so those files work as well. 

My main issue is that every single file is updated, even for projects that don't have references to the project I'm changing the name of. I guess the header is changed, because SourceTree highlights the first line as changed and I don't see a difference. I discarded the changed in the irrelevant project and accepted the changed in the renamed project. Apparently even the images are updated, because all of them became corrupt.

I really hope you can address at least the second issue, because editing all files should not be necessary.

**Comment by kuanysh-nabiyev** [comment]
@brinkdinges Thanks. I am glad that the extension is helpful.
The extension does not change solution name even if they are same. It's not intended for solution renaming.
Renaming namespaces option is on beta stage. And I want to gather more error to fix them to release new version. Thanks to you I know that images can corrupt. Sorry for that.
I thought about renaming namespaces in XAML files, but I was afraid that I can break them. Because I don't know all cases.
